name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: upvoted-archiver
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
    - run: nix flake check
